In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pyodbc

# Connection settings

In [2]:
SERVER   = "Soundes\SQLEXPRESS"   
DATABASE = "Asysenap"

<>:1: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
<>:1: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
C:\Users\dell\AppData\Local\Temp\ipykernel_6016\1480649599.py:1: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
  SERVER   = "Soundes\SQLEXPRESS"

# AUTH METHOD :

In [3]:
conn_str = (
    f"DRIVER={{ODBC Driver 17 for SQL Server}};"
    f"SERVER={SERVER};"
    f"DATABASE={DATABASE};"
    f"Trusted_Connection=yes;"
)

# Load data

In [4]:
conn = pyodbc.connect(conn_str)
query = "SELECT * FROM ACCESLOGICIEL"   # ← change this
df = pd.read_sql(query, conn)
conn.close()
print("✅ Data loaded successfully")

✅ Data loaded successfully

C:\Users\dell\AppData\Local\Temp\ipykernel_6016\272344768.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

In [5]:
print(df.shape)
df

(25, 22)

,matricule,nom,prenom,Structure,passe,utilisateur,syscom,achats,gds,PLANNING_PF,...,SIMULATION,PINVENTAIRE,COMPTABILITE,SYSPCO,UNITEPAIE,IMMOBILISATION,GLOBUPSA,OEUVRE,COOP,GPR
0,04651F,BOUMAIZA,MOURAD,INFORMATIQUE,peinture,Administrateur,1,1,1,1,...,1,1,1,1,1,1,1.0,1.0,1.0,1.0
1,None,ATTIK,A/SALAH,DAF,analyse,attik,0,0,0,0,...,0,0,1,0,1,1,1.0,1.0,0.0,NaN
2,None,AYARI,None,PAIE,beya,ayari,0,0,0,0,...,0,0,0,0,1,0,NaN,NaN,NaN,NaN
3,None,BELOUAER,AMEUR,METHODE,hacene,enapmeth1,0,0,0,0,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
4,None,BELOUAER,DJAMILA,LABO,matiere,devellopeur,0,0,0,0,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
5,None,KHIARI,SALIM,PLANNING,peinture,khiari,0,0,0,1,...,1,0,0,0,0,0,NaN,NaN,NaN,NaN
6,None,NATECHE,ZINE EDDINE,PLANNING,None,nateche,0,0,0,1,...,1,0,0,0,0,0,NaN,NaN,NaN,NaN
7,None,AMMARA,FARID,PLANNING,None,None,0,0,0,1,...,1,0,0,0,0,0,NaN,NaN,NaN,NaN
8,None,TOUAHRIA,OUAHID,FINANCE,finance,ouahid,0,0,0,0,...,0,0,1,0,0,0,NaN,NaN,NaN,NaN
9,None,SOUALEM,FAOUZI,DIRECTION,tableau,soualem,1,1,1,1,...,1,1,1,1,1,1,NaN,NaN,NaN,NaN
10,None,MOUSSAOUI,BILLEL,VENTES,corededuo,vendeur,1,0,0,0,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
11,None,BOUCHOUK,LEILA,PCO,None,None,0,0,0,0,...,0,0,0,1,0,0,NaN,NaN,NaN,NaN
12,None,LALAIBIA,BRAHIM,ACHATS,None,gestion,0,1,0,0,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
13,None,BOUTERAA,AMAR,PRODUCTION,None,producteur,0,0,0,1,...,1,0,0,0,0,0,NaN,NaN,NaN,NaN
14,None,RAMAS,SLIMANE,LABO,hiro,RAMAS,0,0,0,0,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
15,,CHABBI,RACHID,LABO,chichi,CHABBI,0,0,0,0,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
16,None,OULACEB,NOURA,LABO,reactif,OULACEB,0,0,0,0,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
17,None,AMMARA,FARID,LABO,achat,COMMERCIAL,1,1,1,0,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
18,None,LABO,LABO,LABO,developpement,LABO,0,0,0,0,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
19,None,SALIM,KHIARI,PLANNING,peinture,salim,0,0,0,1,...,1,0,0,0,0,0,NaN,NaN,NaN,NaN
20,None,SALIM1,KHIARI1,PLANNING,peinture,khiarisalim,0,0,0,1,...,1,0,0,0,0,0,NaN,NaN,NaN,NaN
21,None,FETTACHE,DJAMILA,LABO,base24*,LABOUPSA,0,0,0,0,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
22,None,LAHFAYA,AMEL,LABO,innovation,LAHFAYA,0,0,0,0,...,0,0,0,0,0,0,1.0,0.0,0.0,NaN
23,None,SAHTOUT,HOUCEM,LABO,++Houcem**,SAHTOUT,0,0,0,0,...,0,0,0,0,0,0,0.0,0.0,0.0,NaN
24,None,FETTACHE,DJAMILA,LABO,base24*,FETTACHE,0,0,0,0,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN

In [6]:
conn = pyodbc.connect(conn_str)
query = "SELECT * FROM ARTIDET"   # ← change this
df = pd.read_sql(query, conn)
conn.close()
print("✅ Data loaded successfully")

C:\Users\dell\AppData\Local\Temp\ipykernel_6016\554628881.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

✅ Data loaded successfully

In [7]:
print(df.shape)
df

(4817, 37)

,CODART,UNITE,NIVEAU,AMORTIS,PERE,COMPOS,LIBCOMPOS,ANAQUI,VAO,VOR,...,DATE_ASSAINI,PV_assaini,FICHE,DIAGNOSTIC,RAPPORT,AVISU,AVISE,NORD,PHOTO,INV_CONS
0,218350135,07,2,True,218350135,001,IMPRIMANTE MULTI FONCTION LASER CANON CO ...,None,88000.00,88000.00,...,NaT,None,None,None,None,None,None,None,None,I
1,218350136,07,2,True,218350136,001,LAPTOP DELL VOSTRO 3400 13-1135 G7 ...,None,69000.00,69000.00,...,NaT,None,None,None,None,None,None,None,None,I
2,218350137,07,2,False,218350137,001,ONDULEUR APC 650 VA - 04 SORTIES ...,None,9250.52,9250.52,...,NaT,None,None,None,None,None,None,None,None,C
3,218350137,07,2,False,218350137,002,ONDULEUR APC 650 VA - 04 SORTIES ...,None,9250.52,9250.52,...,NaT,None,None,None,None,None,None,None,None,C
4,218350137,07,2,False,218350137,003,ONDULEURS APC 650 VA - 04 SORTIES ...,None,9250.52,9250.52,...,NaT,None,None,None,None,None,None,None,None,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4812,218350116,07,2,True,218350116,009,UC HP PRODESK 600 G1/INTELCORE ...,None,77145.60,77145.60,...,NaT,None,None,None,None,None,None,None,None,I
4813,218350116,07,2,True,218350116,010,ECRAN ...,None,19286.40,19286.40,...,NaT,None,None,None,None,None,None,None,None,C
4814,218310195,07,2,True,218310195,001,POINTEUSE BIOMETRIQUE ZKTECO IN01 ...,None,36470.58,36470.58,...,NaT,None,None,None,None,None,None,None,None,I
4815,218320118,07,2,True,218320118,001,HACHOIR DE VIANDE EN INOX N°32 ...,None,146000.00,146000.00,...,NaT,None,None,None,None,None,None,None,None,I
4816,212140001,07,2,True,212140001,001,AMEN/SOUTENEMENT DU TALUS COTE SUD BLOC ...,None,1282378.33,1282378.33,...,NaT,None,None,None,None,None,None,None,None,I